// Uruguayan cities and towns offered as suggestions (native <datalist>) on
// every city input — free text still allowed, so places abroad or missing
// towns can simply be typed. Ordered alphabetically.
export const UY_CITIES: string[] = [
  'Aiguá',
  'Artigas',
  'Atlántida',
  'Barra de Valizas',
  'Barros Blancos',
  'Bella Unión',
  'Canelones',
  'Cardona',
  'Carmelo',
  'Castillos',
  'Chuy',
  'Ciudad de la Costa',
  'Ciudad del Plata',
  'Colonia del Sacramento',
  'Colonia Valdense',
  'Dolores',
  'Durazno',
  'Ecilda Paullier',
  'Florida',
  'Fray Bentos',
  'Fray Marcos',
  'Guichón',
  'José Ignacio',
  'José Pedro Varela',
  'Juan Lacaze',
  'La Barra',
  'La Floresta',
  'La Paloma',
  'La Paz',
  'La Pedrera',
  'Las Piedras',
  'Lascano',
  'Libertad',
  'Maldonado',
  'Melo',
  'Mercedes',
  'Minas',
  'Montevideo',
  'Nueva Helvecia',
  'Nueva Palmira',
  'Nuevo Berlín',
  'Ombúes de Lavalle',
  'Pan de Azúcar',
  'Pando',
  'Parque del Plata',
  'Paso de los Toros',
  'Paysandú',
  'Piriápolis',
  'Progreso',
  'Punta del Diablo',
  'Punta del Este',
  'Quebracho',
  'Río Branco',
  'Rivera',
  'Rocha',
  'Rosario',
  'Salinas',
  'Salto',
  'San Carlos',
  'San Gregorio de Polanco',
  'San Jacinto',
  'San José de Mayo',
  'San Javier',
  'San Ramón',
  'Santa Clara de Olimar',
  'Santa Lucía',
  'Santa Rosa',
  'Sarandí del Yí',
  'Sarandí Grande',
  'Sauce',
  'Solís de Mataojo',
  'Tacuarembó',
  'Tala',
  'Tarariras',
  'Toledo',
  'Tranqueras',
  'Treinta y Tres',
  'Trinidad',
  'Vergara',
  'Vichadero',
  'Young',
]
